- link:
    $HOME/.config/bat:
      path: packages/bat

- shell:
    - command: |
        if [ -x "$(command -v bat)" ]; then
          bat cache --build
        else
          batcat cache --build
        fi
