# mac
- link:
    $HOME/Library/Application Support/lazygit/config.yml:
      if: '[ "$(uname -s)" = "Darwin" ]'
      path: lazygit/config.yml

# linux
- link:
    $HOME/.config/lazygit/config.yml:
      if: '[ "$(uname -s)" = "Linux" ]'
      path: lazygit/config.yml
