- link:
    $HOME/.lessfilter:
      path: packages/lesspipe/lessfilter

# linux
- link:
    $HOME/lesspipe.sh:
      if: '[ "$(uname -s)" = "Linux" ] && [ ! "$(uname -m)" = "amd64" ]'
      path: packages/lesspipe/script/lesspipe.sh
