- link:
    $HOME/.lessfilter:
      path: packages/lesspipe/lessfilter

# linux
- link:
    $HOME/lesspipe.sh:
      if: '[ "$(uname -s)" = "Linux" ] && [ "$(uname -m)" = "aarch64" ]'
      path: packages/lesspipe/script/lesspipe.sh
