- shell:
    - description: Clone p10k repo
      command: |
        if [ "$(uname -m)" = "i686" ]; then
          if [[ ! -d $HOME/.zsh/custom/themes/powerlevel10k ]]; then
            git clone --depth=1 https://github.com/romkatv/powerlevel10k $HOME/.zsh/custom/themes/powerlevel10k
          fi
        else
          echo romkatv/powerlevel10k >> ~/.zsh/.zplugins
        fi

- link:
    $HOME/.zsh/.p10k.zsh: packages/p10k/.p10k.zsh

- shell:
    - description: Initialise plugins
      command: zsh -i -c exit
