- shell:
    - description: Clone p10k repo
      command: |
        if [[ ! -d $ZSH/custom/themes/powerlevel10k ]]; then
          git clone https://github.com/romkatv/powerlevel10k $ZSH/custom/themes/powerlevel10k
        fi

- link:
    $HOME/.zsh/.p10k.zsh: packages/p10k/.p10k.zsh
