- shell:
    - description: Clone p10k repo
      command: |
        repo=romkatv/powerlevel10k
        if [[ ! -d $ZSH/custom/themes/${repo:t} ]]; then
          git clone https://github.com/${repo} $ZSH/custom/themes/${repo:t}
        fi
        unset repo
        unset theme_repos

- link:
    $HOME/.zsh/.p10k.zsh: packages/p10k/.p10k.zsh
