# mac
- link:
    $HOME/.config/sesh/sesh.toml:
      if: '[ "$(uname -s)" = "Darwin" ]'
      path: sesh/sesh.mac.toml

# linux (android)
- link:
    $HOME/.config/sesh/sesh.toml:
      if: '[ "$(uname -s)" = "Linux" ] && [ "$(uname -m)" = "aarch64" ]'
      path: sesh/sesh.termux.toml

# linux (steamos)
- link:
    $HOME/.config/sesh/sesh.toml:
      if: '[ "$(uname -s)" = "Linux" ] && [ "$(uname -m)" = "x86_64" ]'
      path: sesh/sesh.deck.toml
