- link:
    $HOME/.config/tmux/tmux.conf: tmux/tmux.conf
    $HOME/.config/tmux/custom:
      path: tmux/custom

- shell:
    - description: Update ncurses for tmux-256color
      command: |
        if [ "$(uname -s)" = "Darwin" ]; then
          tmp_dir=$(mktemp -d)

          curl --output-dir "$tmp_dir" -LO https://invisible-island.net/datafiles/current/terminfo.src.gz
          gunzip "$tmp_dir"/terminfo.src.gz

          echo "Updating terminfo"
          /usr/bin/tic -xe tmux-256color "$tmp_dir/terminfo.src"
        fi
      stdout: true
      stdin: true
