- link:
    $HOME/.zsh/.zshrc: packages/zsh/zshrc
    $HOME/.zsh/.zprofile: packages/zsh/zprofile
    $HOME/.zsh/.zshenv: packages/zsh/zshenv
    $HOME/.zsh/.zplugins: packages/zsh/zplugins

    $HOME/.zshenv: packages/zsh/shim.zshenv

    $HOME/.zsh/custom:
      path: packages/zsh/custom/*
      glob: true

    $HOME/.zsh/completions:
      path: packages/zsh/completions

- shell:
    - description: Making zsh the default shell
      command: chsh -s $(which zsh)

    - description: Install ohmyzsh if running on ish
      command: |
        if [[ ! -d $ZDOTDIR/ohmyzsh ]] && [[ "$(cat /etc/hostname | grep 'myk-ipad-ish')" ]]; then
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        fi

    - description: Clone zsh plugin repos if running on ish
      command: |
        if [[ "$(cat /etc/hostname | grep 'myk-ipad-ish')" ]]; then
          repos=(
            aloxaf/fzf-tab
            zsh-users/zsh-completions
            zdharma-continuum/fast-syntax-highlighting
            zsh-users/zsh-autosuggestions
          )
          for repo in $repos; do
            if [[ ! -d $ZDOTDIR/ohmyzsh/plugins/${repo:t} ]]; then
              git clone https://github.com/${repo} $ZDOTDIR/ohmyzsh/plugins/${repo:t}
            fi
          done
          unset repo{s,}
        fi
