name = "install-dotfiles"
compatibility_date = "2025-06-15"

routes = [
  { pattern = "dot.myk.rocks", custom_domain = true },
  { pattern = "env.myk.rocks", custom_domain = true },
  { pattern = "env.myk.rest", custom_domain = true },
]

[assets]
directory = "./scripts/page/"
