#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME" || return

echo "Init submodules"
yadm submodule update --recursive --init

system_type=$(uname -s)
tmp_dir=$(mktemp -d)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  fi

  # Update ncurses for tmux-256color
  curl --output-dir "$tmp_dir" -LO https://invisible-island.net/datafiles/current/terminfo.src.gz
  gunzip "$tmp_dir"/terminfo.src.gz
  /usr/bin/tic -xe tmux-256color terminfo.src

fi
