- apt:
    - dialog
    - apt-utils
    - apt-transport-https
    - git
    - gpg
    - curl
    - wget
    - less
    - python3
    - python3-pip
    - python-is-python3
    - zip
    - unzip
    - ncdu
    - xdg-user-dirs
    - zsh
    - fd-find
    - ripgrep
    - fzf
    - bat
    - htop
    - tmux
    - neovim

- shell:
    - description: Install zoxide
      command: curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash

    - description: Add eza repo to apk
      command: |
        mkdir -p /etc/apt/keyrings
        wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
        echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
        chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list

- apt:
    - eza
