- apt:
    - apt-utils
    - apt-transport-https
    - git
    - gpg
    - libc6-dev
    - gcc
    - make
    - curl
    - wget
    - less
    - python3
    - python3-pip
    - python-is-python3
    - zip
    - unzip
    - ncdu
    - xdg-user-dirs
    - zsh
    - fd-find
    - ripgrep
    - jq
    - zoxide
    - fzf
    - bat
    - htop
    - tmux
    - neovim

- shell:
    - mkdir -p /etc/apt/keyrings
    - [
        wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | gpg --yes --dearmor -o /etc/apt/keyrings/gierens.gpg,
        Loading eza repo keys,
      ]
    - echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
    - chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list

- apt:
    - eza
