- apt:
    - fonts-noto
    - fonts-noto-color-emoji
    - fonts-jetbrains-mono
    - alacritty
- shell:
    - command: |
        echo To install Nerd Font
        echo bash -c  \"$\(curl -fsSL https://raw.githubusercontent.com/officialrajdeepsingh/nerd-fonts-installer/main/install.sh\)\"
