- apt:
    - build-essential
    - git
    - python3
    - python3-pip
    - libncurses-dev
    - zip
    - unzip
    - ncdu
    - xdg-user-dirs
    - zsh
    - tmux
    - fd-find
    - ripgrep
    - zoxide
    - fzf
    - ffmpeg
    - 7zip
    - jq
    - poppler-utils
    - imagemagick
    - eza
    - bat
    - neovim

- shell:
    - command: xdg-user-dirs-update

    - description: Install starship shell (yes curl|sh bc y not)
      command: curl -sS https://starship.rs/install.sh | sh -s -- -y

    - description: Install lazygit
      command: |
        LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | \grep -Po '"tag_name": *"v\K[^"]*')
        curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v${LAZYGIT_VERSION}/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
        tar xf lazygit.tar.gz lazygit
        install lazygit -D -t /usr/local/bin/
        rm -rf lazygit*

    - description: Install yazi
      command: |
        curl -L https://github.com/sxyazi/yazi/releases/latest/download/yazi-aarch64-unknown-linux-musl.zip -o yazi.zip
        unzip yazi.zip
        install yazi-aarch64-unknown-linux-musl/yazi -d -t /usr/local/bin/
        install yazi-aarch64-unknown-linux-musl/ya -d -t /usr/local/bin/
        cp yazi/completions/_yazi ~/.zsh/completions
        cp yazi/completions/_ya ~/.zsh/completions
        rm -rf yazi*

    # - description: Change shell to zsh
    #   command: chsh -s $(which zsh)
