- apt:
    - ffmpeg
    - 7zip
    - jq
    - poppler-utils
    - fd-find
    - ripgrep
    - fzf
    - zoxide
    - imagemagick

- shell:
    - description: Install yazi
      command: |
        curl -L https://github.com/sxyazi/yazi/releases/latest/download/yazi-aarch64-unknown-linux-musl.zip -o yazi.zip
        unzip yazi.zip
        sudo install yazi-aarch64-unknown-linux-musl/yazi -d -t /usr/local/bin/
        sudo install yazi-aarch64-unknown-linux-musl/ya -d -t /usr/local/bin/
        cp yazi/completions/_yazi ~/.zsh/completions
        cp yazi/completions/_ya ~/.zsh/completions
        rm -rf yazi*
