- apk:
    - git
    - curl
    - wget
    - openssh
    - gzip
    - unzip
    - bash
    - zsh
    - grep
    - fd@community
    - ripgrep@community
    - alpine-sdk
    - libc-dev
    - make
    - python3
    - libstdc++
