- apk:
    - git
    - curl
    - wget
    - openssh
    - gzip
    - unzip
    - bash
    - zsh
    - fd
    - grep
    - ripgrep
    - alpine-sdk
    - libc-dev
    - make
    - python3
    - libstdc++
