- apk:
    - openrc openssh git shadow alpine-conf

- shell:
    - command: |
        rc-update add sshd default && \
        echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
    - description: Setup hostname
      command: setup-hostname -n myk-alpine-docker

- apk:
    - zip unzip gzip ncdu xdg-user-dirs grep curl wget
    - bash zsh tmux starship
    - fd ripgrep jq
    - coreutils musl build-base openssl
    - python3-dev=~3.12 uv
    - zoxide fzf eza bat htop
    - neovim lazygit
- link:
    $HOME/.zsh/custom/locale.zsh:
      path: packages/arch/locale.zsh
