- apk:
    - git curl wget openssh gzip unzip grep
    - bash # zsh
    # - fd@community ripgrep@community
    - build-base libstdc++ coreutils automake autoconf pkgconf libtool # alpine-sdk
    - python3 uv@community
