- apk:
    - alpine-sdk
    - libstdc++ musl-dev openssl-dev linux-headers automake autoconf pkgconf libtool
    - rust cargo
    - go lua-language-server
    - nodejs npm github-cli

- shell:
    - descriprion: Install neovim plugins
      command: bash ./scripts/install-nvim-plugins.sh
