- apt:
    - apt-utils
    - apt-transport-https
    - git
    - curl
    - wget
    - less
    - python3
    - python3-pip
    - python-is-python3
    - zip
    - unzip
    - ncdu
    - xdg-user-dirs
    - zsh
    - tmux
    - fd-find
    - ripgrep
    - zoxide
    - fzf
    - eza
    - bat
    - htop
    - neovim
