- apt:
    - apt-utils
    - fakeroot
    - build-essential
    - apt-transport-https
    - git
    - gcc
    - make
    - curl
    - wget
    - less
    - dbus
    - file
    - patch
    - python3
    - python3-pip
    - python-is-python3
    - libncurses-dev
    - zip
    - unzip
    - ncdu
    - xdg-user-dirs
    - zsh
    - tmux
    - fd-find
    - ripgrep
    - zoxide
    - fzf
    - eza
    - bat
    - jq
    - htop
    - vim

- shell:
    - command: xdg-user-dirs-update
