- apt:
    - apt-utils
    - apt-transport-https
    - git
    - curl
    - wget
    - python3
    - python3-pip
    - python-is-python3
    - zip
    - unzip
    - ncdu
    - xdg-user-dirs
    - zsh
    - tmux
    - fd-find
    - ripgrep
    - zoxide
    - fzf
    - eza
    - bat
    - htop
    - neovim

- shell:
    - command: xdg-user-dirs-update

    - description: Install starship shell (yes curl|sh bc y not)
      command: curl -sS https://starship.rs/install.sh | sh -s -- -y
