- apt:
    - build-essential
    - fakeroot
    - dbus
    - file
    - patch
    - libncurses-dev
    - rustup

- shell:
    - description: Install golang
      command: |
        export GO_TMP_DIR=$(mktemp -d)
        git clone https://github.com/udhos/update-golang $GO_TMP_DIR
        bash $GO_TMP_DIR/update-golang.sh

    - description: Install rust
      command: rustup default stable

    # - description: Install sesh
    #   command: go install github.com/joshmedeski/sesh@latest
