- apt:
    - build-essential
    - fakeroot
    - gcc
    - make
    - less
    - dbus
    - file
    - patch
    - libncurses-dev
    - jq

- shell:
    - description: Install sesh
      command: go install github.com/joshmedeski/sesh@latest
