- yay:
    - base-devel
    - ncurses
    - zip
    - unzip
    - ncdu
    - xdg-user-dirs
    - git
    - zsh
    - tmux
    - python
    - starship
    - zoxide
    - fd
    - ripgrep
    - fzf
    - eza
    - bat
    - yazi
    - neovim
    - lazygit
    - github-cli

- link:
    $HOME/.zsh/custom/locale.zsh:
      path: packages/arch/locale.zsh
    $HOME/.zsh/custom/ssh-agent.zsh:
      path: packages/arch/ssh-agent.zsh

- shell:
    - command: xdg-user-dirs-update
    - command: sudo -n install -D -m644 packages/arch/locale.conf /etc/locale.conf
