- yay:
    - base-devel git python uv ncurses
    - zip unzip ncdu xdg-user-dirs
    - zsh tmux starship
    - fd ripgrep
    - zoxide fzf eza bat yazi htop
    - neovim lazygit github-cli

- link:
    $HOME/.zsh/custom/locale.zsh:
      path: packages/arch/locale.zsh
    $HOME/.zsh/custom/ssh-agent.zsh:
      path: packages/arch/ssh-agent.zsh

- shell:
    - command: xdg-user-dirs-update
    - command: install -D -m644 packages/arch/locale.conf /etc/locale.conf
