- yay:
    - base-devel git python uv ncurses pacman-contrib networkmanager
    - zip unzip ncdu xdg-user-dirs curl wget
    - zsh tmux starship
    - fd ripgrep jq sesh-bin
    - zoxide fzf eza bat yazi htop
    - neovim lazygit github-cli

- link:
    $HOME/.zsh/custom/locale.zsh:
      path: packages/arch/locale.zsh

- shell:
    - command: install -D -m644 packages/arch/locale.conf /etc/locale.conf
