- yay:
    - base-devel
    - ncurses
    - zip
    - unzip
    - xdg-user-dirs
    - git
    - zsh
    - tmux
    - python
    - go
    - starship
    - zoxide
    - fzf
    - eza
    - bat
    - neovim
    - lazygit

- shell:
    - command: xdg-user-dirs-update
