- yay:
    - qemu-guest-agent
    - spice-vdagent
    - vulkan-virtio
    - qemu-hw-display-virtio-gpu-pci
    - qemu-hw-display-virtio-gpu-pci-gl
    - networkmanager
    - pipewire
    - pipewire-alsa
    - pipewire-pulse
    - pipewire-jack
    - wireplumber

- link:
    - /usr/local/bin/resize: packages/arch/utm-resolution-fix/resize.sh
    - /etc/udev/rules.d/10-resize.rules: packages/arch/utm-resolution-fix/resize.rules

- shell:
    - command: sudo systemctl enable --now NetworkManager
    - command: sudo systemctl enable --now spice-vdagentd
