- yay:
    - qemu-guest-agent
    - spice-vdagent
    - vulkan-virtio
    - qemu-hw-display-virtio-gpu-pci
    - qemu-hw-display-virtio-gpu-pci-gl
    - networkmanager
    - pipewire
    - pipewire-alsa
    - pipewire-pulse
    - pipewire-jack
    - wireplumber

- shell:
    - command: sudo systemctl enable --now NetworkManager
    - command: sudo systemctl enable --now spice-vdagentd
