- yay:
    - xorg
    - xorg-xinit
    - xorg-xauth
    - xsel
    - polkit
    - greetd
    - greetd-tuigreet

- link:
    $HOME/.Xresources: packages/arch/.Xresources

- shell:
    - command: sudo -n systemctl enable --now greetd
    - command: sudo -n install -D -m644 packages/arch/greetd-config.toml /etc/greetd/config.toml
