- yay:
    - xorg
    - xorg-xinit
    - xorg-xauth
    - xclip
    - polkit
    - greetd
    - greetd-tuigreet

- shell:
    - command: sudo systemctl enable --now greetd
    - command: sudo -n install -D -m644 packages/arch/greetd-config.toml /etc/greetd/config.toml
