- yay:
    - xorg
    - xorg-xinit xorg-xauth
    - xsel xterm

- link:
    $HOME/.Xresources: packages/arch/.Xresources

- shell:
    - command: sudo -n systemctl enable --now greetd
    - command: sudo -n install -D -m644 packages/arch/greetd-config.toml /etc/greetd/config.toml
    - command: sudo -n install -D -m644 packages/arch/utm-resolution-fix/resize.sh /usr/local/bin/resize
    - command: sudo -n install -D -m644 packages/arch/utm-resolution-fix/resize.rules /etc/udev/rules.d/10-resize.rules
