[[session]]
name = "home \U0001F3E1"
path = "~"
startup_command = "la"

[[session]]
name = "downloads \U0001F4E5"
path = "~/Downloads"
startup_command = "y"

[[session]]
name = "documents \U0001F4CB"
path = "~/Documents"
startup_command = "y"

[[session]]
name = "zsh config \U00002699\U0000FE0F"
path = "~"
startup_command = "nvim .zshrc .zprofile .zshenv .zplugins .zaliases .zstyles"

[[session]]
name = "tmux config \U0001F4DF"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "neovim config \U0001F4BE"
path = "~/.config/nvim"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "config dir \U0001F4C1"
path = "~/.config"
startup_command = "nvim -c ':Neotree' -c ':Telescope oldfiles only_cwd=true'"

[[session]]
name = "lyadm \U0001F39B"
path = "~/.local/share/yadm"
startup_command = "lyadm"

[[session]]
name = "macbook SSH \U0001F4BB"
path = "~"
startup_command = "ssh myk-laptop"

[[session]]
name = "termux SSH \U0001F4F1"
path = "~"
startup_command = "ssh termux"
