[[session]]
name = "home \U0001F3E1"
path = "~"
startup_command = "la"

[[session]]
name = "downloads \U0001F4E5"
path = "~/Downloads"
startup_command = "y"

[[session]]
name = "documents \U0001F4CB"
path = "~/Documents"
startup_command = "y"

[[session]]
name = "_dotfiles \U0001F4C1"
path = "~/.dotfiles"
startup_command = "nvim -c ':Neotree' -c ':FzfLua oldfiles'"

[[session]]
name = "zsh config \U00002699\U0000FE0F"
path = "~/.dotfiles/packages/zsh"
startup_command = "nvim zshrc zprofile zshenv zplugins"

[[session]]
name = "tmux config \U0001F4DF"
path = "~/.dotfiles/packages/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "nvim config \U0001F4BE"
path = "~/.dotfiles/packages"
startup_command = "nvim -c ':FzfLua oldfiles cwd=nvim'"

[[session]]
name = "termux SSH \U0001F4F1"
path = "~"
startup_command = "ssh termux"

[[session]]
name = "deck SSH \U0001F3AE"
path = "~"
startup_command = "ssh steamdeck"

[[session]]
name = "ipad arch utm SSH \U0001F4E6"
path = "~"
startup_command = "ssh ipad-arch-utm"

[[session]]
name = "local utm SSH \U0001F3D7"
path = "~"
startup_command = "ssh local-utm"
