[[session]]
name = "\U0001F3E1 Home"
path = "~"
startup_command = "la"

[[session]]
name = "\U0001F4E5 Downloads"
path = "~/Downloads"
startup_command = "y"

[[session]]
name = "\U0001F4CB Documents"
path = "~/Documents"
startup_command = "y"

[[session]]
name = "\U00002699\U0000FE0F  zsh config"
path = "~"
startup_command = "nvim .zshrc .zprofile .zshenv .zplugins .zaliases .zstyles"

[[session]]
name = "\U0001F4DF tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "\U0001F4BE neovim config"
path = "~/.config/nvim"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "\U0001F4C1 config dir"
path = "~/.config"
startup_command = "nvim -c ':Neotree' -c ':Telescope oldfiles only_cwd=true'"

[[session]]
name = "\U0001F39B lyadm lazygit"
path = "~/.local/share/yadm"
startup_command = "lyadm"

[[session]]
name = "\U0001F4BB Macbook SSH"
path = "~"
startup_command = "ssh myk-laptop"

[[session]]
name = "\U0001F4F1 Termux SSH"
path = "~"
startup_command = "ssh termux"
