name: Docker publish arm images

on:
  push:
    branches:
      - "main"
      - "testing"

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          docker-images: false
          large-packages: false

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mnb3000/dotfiles-image
          tags: |
            type=ref,event=branch,suffix=-${{ github.run_number }}
            type=ref,event=branch

      - name: Build and push
        uses: docker/bake-action@v5
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: all-arm
          push: true
        env:
          RELEASE: ${{ steps.extract_branch.outputs.branch }}
